frequency: 30.0  # Hz, adjust based on your system
two_d_mode: true  # Restrict to SE(2): x, y, yaw
transform_time_offset: 0.0
transform_timeout: 0.0
publish_tf: true
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: map

# # Odometry sensor
# odom0: /odom
# odom0_config: [true,  true,  false,   # x, y, z
#                false, false, true,    # roll, pitch, yaw
#                true,  false, false,   # vx, vy, vz
#                false, false, true,    # vroll, vpitch, vyaw
#                false, false, false]    #ax, ay, az 
# odom0_differential: false
# odom0_queue_size: 10
# odom0_pose_rejection_threshold: 5.0
# odom0_twist_rejection_threshold: 1.0

#Increase position covariance to reduce trust in odometry
odom0_pose_covariance: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0,    # x (was 0.001)
                        0.0, 0.1, 0.0, 0.0, 0.0, 0.0,    # y (was 0.001)
                        0.0, 0.0, 1000000.0, 0.0, 0.0, 0.0,  # z
                        0.0, 0.0, 0.0, 1000000.0, 0.0, 0.0,  # roll
                        0.0, 0.0, 0.0, 0.0, 1000000.0, 0.0,  # pitch
                        0.0, 0.0, 0.0, 0.0, 0.0, 1000.0]     # yaw

# IMU sensor
imu0: /losi/witmotion_imu/imu
imu0_config: [false, false, false,   # x, y, z
              false, false, true,    # roll, pitch, yaw
              false, false, false,   # vx, vy, vz
              false, false, true,    # vroll, vpitch, vyaw
              false, false, false]    #ax, ay, az 
imu0_differential: false
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: false

# GPS (converted to odometry)
gps0: /losi/f9p_rover/fix
gps0_config: [true,  true,  false,   # x, y, z
               false, false, false,   # roll, pitch, yaw
               false, false, false,   # vx, vy, vz
               false, false, false,   # vroll, vpitch, vyaw
               false, false, false]    #ax, ay, az 
gps0_differential: false
gps0_queue_size: 10
gps0_pose_rejection_threshold: 5.0

# Decrease position covariance to increase trust in GPS
gps0_pose_covariance: [0.002, 0.0, 0.0, 0.0, 0.0, 0.0,    # x (was 0.005625)
                        0.0, 0.002, 0.0, 0.0, 0.0, 0.0,    # y (was 0.005625)
                        0.0, 0.0, 0.01, 0.0, 0.0, 0.0,     # z (was 0.011236)
                        0.0, 0.0, 0.0, 1000000.0, 0.0, 0.0,  # roll
                        0.0, 0.0, 0.0, 0.0, 1000000.0, 0.0,  # pitch
                        0.0, 0.0, 0.0, 0.0, 0.0, 1000000.0]  # yaw

# Initial state covariance
initial_estimate_covariance: [1e-9, 0,    0,    0,    0,    0,
                              0,    1e-9, 0,    0,    0,    0,
                              0,    0,    1e9,  0,    0,    0,
                              0,    0,    0,    1e9,  0,    0,
                              0,    0,    0,    0,    1e9,  0,
                              0,    0,    0,    0,    0,    1e-9]